[Project]
    name = "test"
    output_dir = "~/Desktop/test_template"
    manage = "pip"
[Serve]
    type = "online"
    api = "REST"
    framework = "fastapi"
[ML]
    framework = "scikit-learn"
    model = "linear_regression"